version: '2'
services:
  postgres:
    image: postgres
    container_name: pg-docker
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=life_stats
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data